url: blog.drombit.com
baseurl: /
destination: ../../site
name: Drombit Blog
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
exclude: ['Rakefile','config.codekit']
paginate: 6
paginate_path: "page:num"
