url: blog.drombit.com
baseurl: /
name: Drombit Blog
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: redcarpet
highlighter: pygments
exclude: ['Rakefile','config.codekit']
paginate: 6
paginate_path: "page:num"
