url: blog.drombit.com
baseurl: /
destination: ../../site
name: Drombit Blog
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude: ['Rakefile','config.codekit']
include: ['.htaccess']
paginate: 6
paginate_path: "page:num"
prose:
  rooturl: '_posts'
  siteurl: 'http://blog.drombit.com'
  media: 'uploads'
  ignore: ['_layouts', '_includes']
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "blog"
