baseurl: /blog-drombit
destination: ../../site
name: Drombit Blog
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude: ['Rakefile','config.codekit']
include: ['.htaccess']
paginate: 6
paginate_path: "page:num"
prose:
  rooturl: '_posts'
  siteurl: 'http://blog.drombit.com'
  media: 'uploads'
  ignore: ['_layouts', '_includes']
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'title'
        field:
          element: 'text'
          label: 'Titulo'
          value: 'Titulo'
      - name: 'description'
        field:
            element: 'textarea'
            label: 'Descripción'
      - name: 'author'
        field:
          element: 'select'
          label: 'Autor'
          options:
            - name: 'Diego'
              value: 'Diego'
            - name: 'Alberto'
              value: 'Alberto'
      - name: 'date'
        field: 
          element: 'text'
          label: 'Fecha'
          value: 'CURRENT_DATETIME'
      - name: 'comments'
        field: 
          element: 'hidden'
          value: "true"
      - name: 'categories'
        field:
          element: 'select'
          label: 'Categorías'
          options:
            - name: 'Diseño'
              value: 'diseno'
            - name: 'Desarrollo'
              value: 'desarrollo'
            - name: 'Opinión'
              value: 'opinion'
      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Añadir Tags'
          alterable: true
          options:
            - name: 'Jekyll'
              value: 'jekyll'
            - name: 'PHP'
              value: 'php'
            - name: 'CSS'
              value: 'css'
            - name: 'HTML'
              value: 'html'




