url: blog.drombit.com
baseurl: /
destination: ../../site
name: Drombit Blog
markdown: redcarpet
highlighter: pygments
kramdown:
    input: GFM
exclude: ['Rakefile','config.codekit']
paginate: 6
paginate_path: "page:num"
