url: blog.drombit.com
baseurl: /
destination: ../../site
name: Drombit Blog
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    enable_coderay: true
    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      inline
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               style
exclude: ['Rakefile','config.codekit']
paginate: 6
paginate_path: "page:num"
