url: blog.drombit.com
baseurl: /
destination: ../../site
name: Drombit Blog
markdown: kramdown
kramdown:
    input: GFM
  
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude: ['Rakefile','config.codekit']
paginate: 6
paginate_path: "page:num"
